import { readFile } from "node:fs/promises";

const root = new URL("..", import.meta.url);
const manifest = await readFile(new URL("pluginbridge-plugin.yaml", root), "utf8");
const pkg = JSON.parse(await readFile(new URL("package.json", root), "utf8"));
const field = (name) => manifest.match(new RegExp(`^${name}:\\s*(.+)$`, "m"))?.[1]?.trim();
const id = field("id");
const version = field("version");
const icon = field("icon_url");
const svg = field("icon_svg_url");
const command = manifest.match(/^command:\s*(\[[^\n]+\])$/m)?.[1];
const nodeRange = manifest.match(/^runtime_dependencies:\n\s+node:\s*["']([^"']+)["']$/m)?.[1];
if (!id || !version || !icon || !svg || !command) throw new Error("manifest must define id, version, both icons, and command");
if (version !== pkg.version) throw new Error(`manifest version ${version} does not equal package version ${pkg.version}`);
if (!/^https:\/\/registry\.npmmirror\.com\/@lobehub\/icons-static-avatar\/latest\/files\/avatars\/[a-z0-9-]+\.webp$/.test(icon)) throw new Error("icon_url must be an approved HTTPS Lobe avatar");
if (!/^https:\/\/registry\.npmmirror\.com\/@lobehub\/icons-static-svg\/latest\/files\/icons\/[a-z0-9-]+\.svg$/.test(svg)) throw new Error("icon_svg_url must be an approved HTTPS Lobe SVG");
if (command.includes("${runtime.node}") && !nodeRange) throw new Error("Node plugins must declare the shared Node runtime");
if (process.env.GITHUB_REF_TYPE === "tag" && process.env.GITHUB_REF_NAME !== `v${version}`) throw new Error("tag, manifest and package versions must agree");
if (!new Set(["macos-arm64", "macos-x64", "windows-x64", "linux-x64"]).has(process.env.PRISM_PLATFORM || "")) throw new Error("invalid release platform");
console.log(JSON.stringify({ id, version, platform: process.env.PRISM_PLATFORM }));
